include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    avoid_redundant_argument_values: true
