name: portfolio
description: Portfolio.
version: 1.0.0+1
publish_to: none
homepage: https://mitulvaghamshi.github.io/

environment:
  sdk: ^3.4.0

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.1.0
  url_launcher: ^6.1.2
  theme_extension:
    path: packages/theme_extension
  layout_breakpoint:
    path: packages/layout_breakpoint

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  theme_extension_builder:
    path: packages/theme_extension_builder

flutter:
  uses-material-design: true
  assets:
    - assets/me.webp
    - assets/wes.webp
    - assets/icon.webp
    - assets/repos.json
