name: Build and Deploy GitHub Pages
on:
  push:
    branches: [ "main" ]
    # paths:
      # - 'portfolio/**'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: macos-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Remove 'repos.json' entry from 'pubspec.yaml'
        shell: bash
        run: |
          sed -i.bak '/assets\/repos.json/d' 'pubspec.yaml';
          if [[ $? -ne 0 ]]; then exit 1; fi
        working-directory: portfolio
      - name: Flutter action
        uses: subosito/flutter-action@v2.23.0
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
        working-directory: portfolio
      - name: Build web
        run: flutter build web
        working-directory: portfolio
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6.0.0
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: 'portfolio/build/web'
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v5.0.0
        id: deployment
